// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOqvU4u0DajsQQ3JYzCVhrxAMUzPArbuU',
    appId: '1:912208080075:android:0d45c583be4767f373ff4e',
    messagingSenderId: '912208080075',
    projectId: 'final-mind-manager',
    storageBucket: 'final-mind-manager.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYYfPaIaOeRD9YEaL0zOjVFflGxTvCxi4',
    appId: '1:912208080075:web:e3e8c197cd1aac8873ff4e',
    messagingSenderId: '912208080075',
    projectId: 'final-mind-manager',
    authDomain: 'final-mind-manager.firebaseapp.com',
    storageBucket: 'final-mind-manager.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAy6kG68QY34Rx6bD4u0xJnVDDD1hzlKY',
    appId: '1:912208080075:ios:4158581d1e998d4b73ff4e',
    messagingSenderId: '912208080075',
    projectId: 'final-mind-manager',
    storageBucket: 'final-mind-manager.firebasestorage.app',
    iosClientId: '912208080075-0dsk65a47ggivballhd6h53es14ojf8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindManagerFinal',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAy6kG68QY34Rx6bD4u0xJnVDDD1hzlKY',
    appId: '1:912208080075:ios:4158581d1e998d4b73ff4e',
    messagingSenderId: '912208080075',
    projectId: 'final-mind-manager',
    storageBucket: 'final-mind-manager.firebasestorage.app',
    iosClientId: '912208080075-0dsk65a47ggivballhd6h53es14ojf8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindManagerFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYYfPaIaOeRD9YEaL0zOjVFflGxTvCxi4',
    appId: '1:912208080075:web:68c093e0e370912873ff4e',
    messagingSenderId: '912208080075',
    projectId: 'final-mind-manager',
    authDomain: 'final-mind-manager.firebaseapp.com',
    storageBucket: 'final-mind-manager.firebasestorage.app',
  );

}